set( CMAKE_SYSTEM_NAME "Windows" )
set( CMAKE_SYSTEM_PROCESSOR "x86" )

set( CMAKE_SHARED_LIBRARY_SUFFIX ".dll" )
set( CMAKE_SHARED_LIBRARY_PREFIX "" )
set( CMAKE_STATIC_LIBRARY_SUFFIX ".lib" )
set( CMAKE_FIND_LIBRARY_SUFFIXES ".lib" )
set( CMAKE_STATIC_LIBRARY_PREFIX "" )