# tier0.cmake

add_library( tier0 IMPORTED SHARED )
set( TIER0_NAME ${CMAKE_SHARED_LIBRARY_PREFIX}tier0${CMAKE_SHARED_LIBRARY_SUFFIX} )
set_target_properties( tier0
	PROPERTIES
		IMPORTED_IMPLIB "${LIBPUBLIC}/${TIER0_NAME}"
		IMPORTED_NO_SONAME true
)
configure_file( "${LIBPUBLIC}/${TIER0_NAME}" "${GAMEDIR}/bin/${TIER0_NAME}" COPYONLY )
