# vstdlib.cmake

add_library( vstdlib IMPORTED SHARED )
set( VSTDLIB_NAME ${CMAKE_SHARED_LIBRARY_PREFIX}vstdlib${CMAKE_SHARED_LIBRARY_SUFFIX} )
set_target_properties( vstdlib
	PROPERTIES
		IMPORTED_IMPLIB "${LIBPUBLIC}/${VSTDLIB_NAME}"
		IMPORTED_NO_SONAME true
)
configure_file( "${LIBPUBLIC}/${VSTDLIB_NAME}" "${GAMEDIR}/bin/${VSTDLIB_NAME}" COPYONLY )
